version: "3.7"
services:
 elasticsearch:
  image: elasticsearch:7.9.1
  container_name: elasticsearch
  environment:
   - discovery.type=single-node
  # volumes:
  #  - 
  ulimits: 
   memlock:
    soft: -1
    hard: -1
  ports:
   - "9200:9200"
   - "9300:9300"
  networks:
    segregate:
      ipv4_address: 192.168.200.18

 kibana:
  image: kibana:7.9.1
  container_name: kibana
  # volumes:
  #  -
  ports:
   - "5601:5601"
  networks:
    segregate:
      ipv4_address: 192.168.200.19
 
 logstash:
    image: logstash:7.9.1
    container_name: logstash
    # volumes:
    #   
    ports:
    - "9600:9600"
    networks: 
      segregate:
        ipv4_address: 192.168.200.20
 nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/my.crt:/etc/ssl/my.crt
      - ./nginx/my.key:/etc/ssl/my.key
    ports:
      - "443:443"
    networks:
      segregate:
        ipv4_address: 192.168.200.21
 

networks:
  segregate:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.16/28

