version: "3.7"
services:
 elasticsearch:
  image: elasticsearch:7.9.1
  container_name: elasticsearch
  environment:
   - discovery.type=single-node
  # volumes:
  #  - 
  ulimits: 
   memlock:
    soft: -1
    hard: -1
  ports:
   - "9200:9200"
   - "9300:9300"
  networks:
    segregate:
      ipv4_address: 192.168.200.18
