version: "3.7"
services: 
  kibana: 
    image: kibana:7.9.1
    container_name: kibana
    volumes:
     - ./kibana/kibana.yml
    ports:
     - "5601:5601"
    networks:
      segregate:
        ipv4_address: 192.168.200.19

networks:
  segregate:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.16/28