version: "3.7"
services:
  logstash:
    image: logstash:7.9.1
    container_name: logstash
    # volumes:
    #   
    ports:
    - "9600:9600"
    networks: 
      segregate:
        ipv4_address: 192.168.200.20

networks:
  segregate:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.16/28